### ISSUE TITLE
HTTP error 429: Too many requests

### ISSUE THREAD

**Issue by SouravKB** [pavitrakumar78/Language-and-Library-usage-analysis-of-GitHub-repositories#1]
This program is giving me _HTTP error 429: Too many requests_. I tried to increase the delay from 6 to 100. But still no luck.

**Comment by pavitrakumar78** [comment]
If you have already made requests, then you have reached the limit for the day - check Github's limits they may have changed as this was written over 5 years ago. 

I just checked running the code for 1 loop and it works. Try it after a few hrs.
